# https://docs.travis-ci.com/user/customizing-the-build/

sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
cache: yarn
branches:
  only:
    - master
    - /^greenkeeper\/.*$/
matrix:
  fast_finish: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
  - export PATH="$HOME/.yarn/bin:$PATH"
script: yarn start ci
